### ISSUE TITLE
allow patterns in keys to be escaped

### ISSUE THREAD

**Issue by jonschlinkert** [doowb/stringify-keys#2]
See: https://github.com/jonschlinkert/glob-object. I'd like to be able to allow users to escape keys if necessary. This isn't urgent, I can do a pr. Might wait until someone actually has a need for it though

**Comment by doowb** [comment]
a PR would be great. I'm assuming that it would work like [get-value](https://github.com/jonschlinkert/get-value/blob/master/index.js#L42-L48)?

**Comment by jonschlinkert** [comment]
yeah, basically just do a replace function, capture and cache the escaped character, then put it back after the slashification

**Comment by doowb** [comment]
Just saw your `split-string` repo and reminded me about this. At first I thought I could use that, but I think the intention is to return escaped keys if they contain the separator. See [this commit](https://github.com/doowb/stringify-keys/commit/c8df94a152a09f2d4f0de5780c0b0475720e0422) and let me know if that's what you're intending.

This will allow something like an object where the keys are filenames containing the extension:

``` js
var files = {
  'foo.hbs': 'foo',
  'bar.hbs': bar
};

var keys = stringify(files);
//=> ['foo\\.hbs', 'bar\\.hbs']
```

Let me know what you think

**Comment by jonschlinkert** [comment]
you gave it more thought than me, I think you did it the right way. Makes sense to return an array of escaped keys so they can be passed directly to get-value. thanks!

**Comment by jonschlinkert** [comment]
closing due to age

**Comment by jonschlinkert** [comment]
actually I'm going to do this really quick
